version: '3'
services:
  consul:
    image: consul
    ports:
    - 8500:8500
    environment:
      CONSUL_BIND_INTERFACE: eth0
      CONSUL_CLIENT_INTERFACE: eth0
  employee:
    image: 03-server-side-service-discovery_employee
    # ports:
    # - 8080:80